- type: custom:button-card
  entity: sensor.discord_user_userid_game_image_large
  show_name: false
  show_state: false
  show_icon: false
  custom_fields:
    image: >
      [[[ if (states['sensor.discord_user_userid_game'].state !== 'unknown') 
      return `<img src="${states["sensor.discord_user_userid_game_image_large"].attributes.entity_picture}" style="width: 75px; height: 75px; border-radius: 10%;">`; 
      return ''; ]]]
    info: >
      [[[ if (states['sensor.discord_user_userid_game'].state === 'unknown') 
      return '<div><b>Not playing game</b></div>'; 
      return `
         <div style="display: flex; flex-direction: column; margin-left: 10px;">
           <div style="font-weight: bold; color: white; margin-bottom: 5px;">
             ${states['sensor.discord_user_userid_game'].state}
           </div>
           <div style="color: gray; margin-bottom: 5px;">
             ${states['sensor.discord_user_userid_game_state'].state}
           </div>
           <div style="color: gray;">
             ${states['sensor.discord_user_userid_game_details'].state}
           </div>
         </div>`; ]]]
  styles:
    card:
      - border-radius: 10px
      - padding: 10px
      - background-color: '#1c1c1c'
      - box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2)
      - color: white
      - display: flex
      - flex-direction: row
      - align-items: center
    custom_fields:
      image:
        - display: flex
        - justify-content: center
        - align-items: center
        - margin-right: 10px
      info:
        - display: flex
        - flex-direction: column
        - justify-content: center
        - align-items: flex-start